vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        reclamation:
            uri_prefix: /images/reclamation
            upload_destination: '%kernel.project_dir%/public/images/reclamations'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer